name: Run tests
permissions:
  contents: read

on: push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 25
          cache: 'npm'
        
      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx biome ci

      - name: Run tests
        run: npm test

      - name: Generate coverage
        run: npm run test:coverage
        continue-on-error: true

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
          flag: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: coverage/junit.xml
          retention-days: 30

  test-summary:
    name: Test summary
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.test.result }}" == "failure" ]; then
            echo "❌ Tests failed"
            exit 1
          elif [ "${{ needs.test.result }}" == "cancelled" ]; then
            echo "⚠️ Tests were cancelled"
            exit 1
          else
            echo "✅ All tests passed"
          fi

      - name: Test Summary
        uses: test-summary@action@v2
        with:
          paths: |
            coverage/
            junit.xml